FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o bot ./cmd/bot

# Финальный образ (минимальный Linux)
FROM debian:12-slim

WORKDIR /app

# Устанавливаем CA сертификаты
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

# Копируем бинарник из builder-образа
COPY --from=builder /app/bot .

# Копируем env-файл если нужно
COPY .env .

# Команда запуска
CMD ["./bot"]